config/routes.rb
Rails.application.routes.draw do

  

  get 'posts/index', to: 'posts#index'

  post 'createcomment', to: 'comments#create', as: 'create_comment'
  post 'anothercomment', to: 'comments#anothercomment', as: 'another_comment'

  
  get 'posts/new', to: 'posts#new', as: 'posts'
  post 'posts/new', to: 'posts#create'

  get 'posts/:id', to: 'posts#show', as: 'post'
  get 'posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  put 'posts/:id', to: 'posts#update'
  patch 'posts/:id', to: 'posts#update'
  delete 'posts/:id', to: 'posts#delete'

  root 'home#homepage'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'destroy_session'
 
  get 'allusers', to: 'users#index'
  get 'new', to: 'users#new'
  post 'users', to: 'users#create'
  get 'users/:id', to: 'users#show', as: 'user'
  post 'users/:id', to: 'users#search'
  get 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  get 'users/contact'
  put 'users/:id', to: 'users#update'
  patch 'users/:id', to: 'users#update'
  delete 'users/:id', to: 'users#delete'

  get 'like' => "posts#like"

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	has_many :commentoncomments
end

app/models/commentoncomment.rb
class Commentoncomment < ActiveRecord::Base
	belongs_to :comment
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/postlike.rb
class Postlike < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_attached_file :image, default_url: "noprofile.jpeg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :posts
  has_many :comments

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :username, length: { minimum: 2 }
  validates :password, presence: true
  validates :password, length: { minimum: 6 }

  # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "noprofile.jpeg"
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	if session[:user_id]
  		User.find(session[:user_id])
  	else
  		nil
  	end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create

  	#puts "******************************"
  	#puts params

  	commentContent = params[:comment][:content]
  	id = session[:user_id]
  	#@postId = params[:hidden]
  	postId = params[:comment][:hidden]
  	@Comment = Comment.create(content: commentContent, user_id: id, post_id: postId) 


  	#redirect_to root_path
	redirect_to post_path postId

  end

  def anothercomment
      commentCommentContent = params[:commentoncomment][:content]
      id = session[:user_id]
      postId = params[:commentoncomment][:hidden]
      commentId = params[:commentoncomment][:hidden2]
      @Comment = Commentoncomment.create(content: commentCommentContent, user_id: id, comment_id: commentId, post_id: postId) 
      redirect_to post_path postId

  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
  	@id = session[:user_id]
  	@myPosts = Post.where(user_id: @id)
  	@posts = Post.all
  	if session[:user_id]
  	  @user = User.find(@id)
  	end
  	if !session[:user_id]
  	  render :layout => false
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all.reverse

  end

  def new
    @post = Post.new
  end

  def create
    #puts "***********************"
    #puts params 

    title = params[:post][:title]
    content = params[:post][:content]
    id = session[:user_id]
    @Post = Post.create(title: title, content: content, user_id: id)

    # @post = Post.create(params.require(:post).permit(:title, :content, :user_id))
    flash[:notice] = "Post Successfully Created by User # #{id}"
    redirect_to root_path
  end

  def show
    @likeAmount = Postlike.all.count
  	@post = Post.find(params[:id])
  	@comment = Comment.where(post_id: params[:id])
    #same as @comment but want to break it up for an easier read
    #@commentcomment = Commentoncomment.where(comment_id: params[:id])
    @counter = 0
    @counter2 = 0
    @newComment = Comment.new
    @newCommentonComment = Commentoncomment.new
  end

  def like
    @liked = Postlike.create(user_id:session[:user_id], post_id:params[:apple])
    @likeAmount = Postlike.all.count
    puts params
    render :layout => false
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    params[:username]
    params[:password]

    @user = User.where(username: params[:username]).first
    
    if @user 
      if @user.password == params[:password] 
        session[:user_id] = @user.id
        flash[:notice] = "Hello #{@user.username}!"
        redirect_to root_path
      else
        flash[:alert] = "Login Not Successful, Please Try Again"
        redirect_to login_path
      end
    else
      flash[:alert] = "Login Not Successful, Please Try Again"
      redirect_to login_path
    end
  end	

  def destroy
    session[:user_id] = nil
    # flash[:notice] = "Successfully Logged Out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
    # puts params 
    # @searchedUser = User.where(username: :search) #add params inside parenthesis?

  end

  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update(params.require(:user).permit(:username, :password, :image))
    flash[:notice] = "User Successfully Updated"
    redirect_to user_path(@user)
  end
  def contact
  end

  def delete
    #wrap if session[:user_id] around this??
    @user = User.find(params[:id]) 
    @user.delete
    redirect_to root_path
    flash[:notice] = 'User Deleted!'
  end
  def create
    @user = User.new(params.require(:user).permit(:username, :password, :image))
    if @user.save
      flash[:notice] = "User Successfully Created"
      redirect_to login_path
    else
      flash[:alert] = "Error Creating User, Please Try Again"
      redirect_to new_path 
    end
  end
  
  def search
    #puts "*************** PARAMS"
    #puts params
    results = User.where(username: params[:search])
    if results.length == 0
      flash[:notice] = "No matches"
      redirect_to allusers_path
    elsif results.length > 1
      @user = results.first
      flash[:notice] = "Multiple #{@user.username}'s found, returning the first result"
      redirect_to user_path(@user)
    else 
      @user = results.first
      redirect_to user_path(@user)
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def link_to_google
    content_tag :h4 do
      link_to "Google Link Test", "http://www.google.com"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!--

╱╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╱╱╱╱╭╮╱╭╮╱╱╱╭╮
╱╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╱╱╱╱╱╱╱╭╯╰╮╱╱╱╱╭╮╱╱╱╱╱┃┃╱┃┃╱╱╱┃┃
╭╮╭╮╭┳━━┫┃╭━━┳━━┳╮╭┳━━╮╰╮╭╋━━╮╱╰╋╮╭┳╮╭┫╰━┫┃╭━╮┃┃
┃╰╯╰╯┃┃━┫┃┃╭━┫╭╮┃╰╯┃┃━┫╱┃┃┃╭╮┃╱╭┫┃┃┃╰╯┃╭╮┃┃┃╭╯╰╯
╰╮╭╮╭┫┃━┫╰┫╰━┫╰╯┃┃┃┃┃━┫╱┃╰┫╰╯┃╱┃┃╰╯┃┃┃┃╰╯┃╰┫┃╱╭╮
╱╰╯╰╯╰━━┻━┻━━┻━━┻┻┻┻━━╯╱╰━┻━━╯╱┃┣━━┻┻┻┻━━┻━┻╯╱╰╯
╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭╯┃
╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━╯

-->
<head>
  <title>jumblr</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Free Blog Website, Join for Free Today, Developed by John Bergandino">
  <meta name="keywords" content="Blog,Free,John,Bergandino">
  <meta name="author" content="John Bergandino">
	<%= favicon_link_tag 'favicon.ico' %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:600italic,400,600,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<ul class="header_links">
			<% if session[:user_id] %>
				<li><%= link_to 'Logout', destroy_session_path %></li>		
				<li><%= link_to 'Preferences', user_path(session[:user_id]) %></li>		
				<li><%= link_to 'See All Users', allusers_path %></li>						
				<li><%= link_to 'Check Latest Posts', posts_index_path %></li>		
				<li><%= link_to 'Create New Post', posts_path %></li>						
				<li><%= link_to 'Home', root_path %></li>
			<% else %>
				<li><%= link_to 'Login', login_path %></li>
				<li><%= link_to 'Create New User', new_path %></li>
				<li><%= link_to 'Home', root_path %></li>
			<% end %>
		</ul>
		<ul class="mobile_header_links">
			<% if session[:user_id] %>
				<li><%= image_tag 'jumblr-logo.gif', :class => 'jumblr_logo_mobile' %></li>
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Create New Post', posts_path %></li>	
				<li><%= link_to 'Check Latest Posts', posts_index_path %></li>	
				<li><%= link_to 'See All Users', allusers_path %></li>	
				<li><%= link_to 'Preferences', user_path(session[:user_id]) %></li>		
				<li><%= link_to 'Logout', destroy_session_path %></li>		
			<% else %>
				<li><%= link_to 'Login', login_path %></li>
				<li><%= link_to 'Create New User', new_path %></li>
				<li><%= link_to 'Home', root_path %></li>
			<% end %>
		</ul>
	
		<%= image_tag 'jumblr-logo.gif', :class => 'jumblr_logo' %>
	</header>
	<div class="linear-gradient">
			<hr class="clearing_hr">
		<div class="body_wrapper">
			<br>
			<% if flash[:notice] %>
				<p class="flash_message"><%= flash[:notice] %></p>
				<br>
			<% end %>
			<% if flash[:alert] %>
				<p class="flash_message"><%= flash[:alert] %></p>
				<br>
			<% end %>
			
			<%= yield %>

			<% if session[:user_id] %>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<p>
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- Initial Responsive Ad -->
					<ins class="adsbygoogle"
					     style="display:block"
					     data-ad-client="ca-pub-8193639314462440"
					     data-ad-slot="5303444617"
					     data-ad-format="auto"></ins>
					<script>
					(adsbygoogle = window.adsbygoogle || []).push({});
					</script>
				</p>
				<footer>
					<p>Currently Signed in as Username: <%= User.find(session[:user_id]).username %> </p>
				</footer>
			<% end %>
		</div>
	</div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</body>
</html>

app/views/posts/index.html.erb
<h1>Recent Blog Posts</h1>
<br>
<br>

<% @posts.each do |post| %>
	
	<% if User.where(id: post.user_id).length > 0 %>
	  <% thisUsername = User.find(post.user_id).username %>
	  <% thisUserPic = User.find(post.user_id).image.url() %>
	  <p> <%= link_to post.title, post_path(post.id)  %> Authored By: <%= thisUsername %> </p> 
	  <div class="thumbs"><%= image_tag thisUserPic %></div>
	  <hr>
	  <br>	 
	<% end %>
<% end %>

app/views/posts/like.html.erb
<%= @likeAmount %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<hr>

<%= form_for @post do |f|  %>
	<p>
		<%= f.label :title %>
	</p>
	<p class="title_content">
		<%= f.text_area :title, size: '90x1', :placeholder => 'Add Your Blog Post Title...' %>
	</p>
	<br class="desktop_break">
	<br>
	<p>
		<%= f.label :content %>
	</p>
	<p class="form_content">
		<%= f.text_area :content, size: '150x30', :placeholder => 'Add Your Blog Post Content...'  %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>


<hr>
<br>
<strong>
	<p> <%= @post.content %> </p>
</strong>
<hr>
<p><%= link_to "Like This Post", like_path(apple: @post.id), method: :get, remote: true, class:"likeButton" %></p>
<p class="runningLikeTotal"><%= @likeAmount %></p>
 <!-- ****************************************************************************************************************************** -->


<div class= "comment_wrapper">
	<br>
	<%= form_for @newComment, url: create_comment_path do |f| %>

		<p class="main_comment_form">
			<%= f.text_area :content, size: '75x1', :placeholder => 'Write A Comment...' %>
		</p>
		<p>
			<%= f.hidden_field :hidden, :value => @post.id %>
		</p>
		<p class="main_comment_form">
			<%= f.submit %>
		</p>

	<% end %>


	<% while @counter < @comment.length %>

		<% 
			@thisCommentId = @comment[@counter].id 
			@commentcomment = Commentoncomment.where(comment_id: @thisCommentId)
		%>
		<div class="larger-thumbs"><%= image_tag User.find(@comment[@counter].user_id).image.url() %></div>
		<p class="comment"> <span class="username_comment"> <%= link_to User.find(@comment[@counter].user_id).username, user_path(User.find(@comment[@counter].user_id).id) %> </span> ~ <%= @comment[@counter].content %> </p>

			
			<div class="replies">
				<!-- loop thru this with a while loop inside of the comment block to add replies underneath-->
				<% while @counter2 < @commentcomment.length  %>
				<div class="thumbs reply"><%= image_tag User.find(@commentcomment[@counter2].user_id).image.url() %></div>
					<p class= "comment_comment"> <span class="username_comment_comment"> <%= link_to User.find(@commentcomment[@counter2].user_id).username, user_path(User.find(@commentcomment[@counter2].user_id).id) %> </span> ~ <%= @commentcomment[@counter2].content %> </p>
					<% @counter2 += 1 %>
				<% end %>
			</div>
		<% @counter2 = 0 %>
		<br>

		<div class="form2">
			<%= form_for @newCommentonComment, url: another_comment_path do |f| %>
				<p class="comment_comment_form">
					<%= f.text_area :content, size: '50x1', :placeholder => 'Write A Reply...' %>
				</p>
				<p>
					<%= f.hidden_field :hidden, :value => @post.id %>
				</p>
				<p>
					<%= f.hidden_field :hidden2, :value => @comment[@counter].id %>
				</p>
				<p class="comment_comment_form">
					<%= f.submit "Reply to Comment" %>
				</p>
			<% end %>
		</div>

		<% @counter += 1 %>
	<% end %>
	<% @counter = 0 %>
</div>

<script type="text/javascript">
	$(".likeButton").on("ajax:complete", function(element, data, status) {

		$(".runningLikeTotal").text(data.responseText);
		console.log("Testing Console!!!")
	});


</script>


<script type="text/javascript">
	
	$(document).on('ready', function(event) {
  // initialize persistent state
  console.log("testConsole")

});

$(document).on('page:fetch', function(event) {
  // apply non-idempotent transformations to the body
  console.log("Test Fetch")
});

$(document).on('page:receive', function(event) {
  // apply non-idempotent transformations to the body
  console.log("Test Receive")
});

</script>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f|  %>

<p>
	<%= f.label :username  %>
	<%= f.text_field :username %>

</p>
<p>
	<%= f.label :password %>
	<%= f.password_field :password %>
</p>
<p>
	<%= f.label :image %>
	<%= f.file_field :image %>
</p>


<p>
	<%= f.submit %>
</p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<br>
<br>
<%= render 'form' %>

app/views/users/index.html.erb
	<h1>Search All Users</h1>
	<br class="desktop_break">

	  <%= form_tag "users/16" do %>
		  <%= label_tag :search %>
	  	  <%= text_field_tag :search %>
	  	  <%= submit_tag "Search"  %>
	  <% end %>



	<% @users.each do |user| %>

		<% if user.id != session[:user_id] %>
			<p><%= link_to user.username, user_path(user.id) %></p>
			<div class="thumbs"><%= image_tag user.image.url() %></div>
		<% end %>

	<% end %>

<!-- <div class="apple linear-gradient"></div> -->

app/views/users/new.html.erb
<h1>Sign Up Below!</h1>
<br>

<%= render 'form' %>

	<div class="apple"></div>

app/views/users/search.html.erb
<p><%= @users %></p>

app/views/users/show.html.erb
<% if session[:user_id] == @user.id %>
	<h3><%= @user.username %>'s Account Preferences</h3>
	<br>
	<br>
	<p><%= link_to 'Edit User', edit_user_path  %></p>
	<br>
	<p><%= link_to 'Delete Account', user_path, method: :delete  %></p>

<% else %>
	
	<br>
	<h1><%= @user.username %></h1>
	<div><%= image_tag @user.image.url() %></div>
	<br>

	<h3><%= @user.username %>'s Posts</h3>

	<% @posts.each do |post| %>

		<p><%= link_to post.title, post_path(post.id) %></p>

	<% end %>


<% end %>